### ISSUE TITLE
lifeSOSpy_MQTT with home assistant in docker container

### ISSUE THREAD

**Issue by bereska** [rorr73/LifeSOSpy_MQTT#2]
hi Robert,
I hate to bother you again
I struggle to have lifesospy_mqtt started after homeassistant restart and I need your help

as you know I have already enabled lifesospy_mqtt as a systemd service and works just fine after pi reboot, everything starts right up
however if I just restart homeassistant ('docker restart homeassistant'), lifesosd.service keeps on running but it never hooks up with homeassistant and I have to manually restart lifesosd.service ('sudo systemctl restart lifesosd.service')

I think the problem is that I run homeassistant in docker container and lifesospy_mqtt was installed on host
I have googled this problem around but could not find a solution
Please let me know your thoughts
regards,
Dmitry

**Comment by rorr73** [comment]
Hi Dmitry,

LifeSOSpy_MQTT should configure itself automatically in Home Assistant as soon as it comes online, provided the following are in place:

1. Home Assistant is configured to enable automatic discovery, and announce when it is online. This is done via it's ``configuration.yaml`` file. Here is the relevant section from mine as an example:
```
mqtt:
  # My Mosquitto broker instance
  broker: 127.0.0.1
  
  # Listen for MQTT clients and automatically configure devices
  discovery: true
  discovery_prefix: 'homeassistant'
  
  # Notify any MQTT clients when we come online and go offline
  birth_message:
    topic: "homeassistant/status"
    payload: 'online'
    qos: 1
    retain: True
  will_message:
    topic: "homeassistant/status"
    payload: 'offline'
    qos: 1
    retain: True
```

2. LifeSOSpy is configured with the correct discovery prefix and birth topic/payload that matches what you have defined in Home Assistant (above). Here is an example from my ``config.yaml``:
```
# Settings for the translator between LifeSOS and MQTT
translator:

  # To automatically configure devices in Home Assistant, ensure this line
  # matches the setting in Home Assistant's config file. Note any devices and
  # switches will need to be assigned a 'ha_name"' to be exported.
  # Refer https://www.home-assistant.io/docs/mqtt/discovery/
  ha_discovery_prefix: homeassistant
  
  # Topic and Payload to announce Home Assistant has come online. When received,
  # our MQTT client will send out the device configurations for discovery.
  ha_birth_topic: homeassistant/status
  ha_birth_payload: online
```

If you change either, you will need to restart HA and/or LifeSOSpy respectively.

How this works is LifeSOSpy subscribes to the birth topic, and when it sees HA announce it is online (which happens every time it starts up), it sends the full configuration of all LifeSOS devices using the homeassistant discovery prefix, so they should appear almost immediately on startup.

If you already have this configuration and it is still not working, the only other thing I can think of is your MQTT broker; are you using a separate instance (eg. [Mosquitto](https://mosquitto.org/)) or the built-in one in Home Assistant? If it is the built-in one, I would suggest trying a Mosquitto Docker instance, as this will ensure the MQTT broker remains running whenever you need to restart HA (ie. it won't sever the connection with LifeSOSpy or any other MQTT clients).
